# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaControlAsistencia.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaControlAsistencia(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(456, 344)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.botonSalir = QtWidgets.QPushButton(Form)
        self.botonSalir.setObjectName("botonSalir")
        self.gridLayout.addWidget(self.botonSalir, 2, 0, 1, 2)
        self.botonRegistrarLlegada = QtWidgets.QPushButton(Form)
        self.botonRegistrarLlegada.setObjectName("botonRegistrarLlegada")
        self.gridLayout.addWidget(self.botonRegistrarLlegada, 1, 0, 1, 1)
        self.botonRegistrarSalida = QtWidgets.QPushButton(Form)
        self.botonRegistrarSalida.setObjectName("botonRegistrarSalida")
        self.gridLayout.addWidget(self.botonRegistrarSalida, 1, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Control de asistencia"))
        self.botonSalir.setText(_translate("Form", "Salir"))
        self.botonRegistrarLlegada.setText(_translate("Form", "Registrar llegada"))
        self.botonRegistrarSalida.setText(_translate("Form", "Registrar salida"))

