# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/VentanaControlAsistencia.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaControlAsistencia(object):
    def setupUi(self, VentanaControlAsistencia):
        VentanaControlAsistencia.setObjectName("VentanaControlAsistencia")
        VentanaControlAsistencia.resize(456, 344)
        self.gridLayout = QtWidgets.QGridLayout(VentanaControlAsistencia)
        self.gridLayout.setObjectName("gridLayout")
        self.botonSalir = QtWidgets.QPushButton(VentanaControlAsistencia)
        self.botonSalir.setObjectName("botonSalir")
        self.gridLayout.addWidget(self.botonSalir, 2, 0, 1, 2)
        self.botonRegistrarLlegada = QtWidgets.QPushButton(VentanaControlAsistencia)
        self.botonRegistrarLlegada.setObjectName("botonRegistrarLlegada")
        self.gridLayout.addWidget(self.botonRegistrarLlegada, 1, 0, 1, 1)
        self.botonRegistrarSalida = QtWidgets.QPushButton(VentanaControlAsistencia)
        self.botonRegistrarSalida.setObjectName("botonRegistrarSalida")
        self.gridLayout.addWidget(self.botonRegistrarSalida, 1, 1, 1, 1)

        self.retranslateUi(VentanaControlAsistencia)
        QtCore.QMetaObject.connectSlotsByName(VentanaControlAsistencia)

    def retranslateUi(self, VentanaControlAsistencia):
        _translate = QtCore.QCoreApplication.translate
        VentanaControlAsistencia.setWindowTitle(_translate("VentanaControlAsistencia", "JEB - Control de asistencia"))
        self.botonSalir.setText(_translate("VentanaControlAsistencia", "Salir"))
        self.botonRegistrarLlegada.setText(_translate("VentanaControlAsistencia", "Registrar llegada"))
        self.botonRegistrarSalida.setText(_translate("VentanaControlAsistencia", "Registrar salida"))

