# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/VentanaInformacionEmpleado.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaInformacionEmpleado(object):
    def setupUi(self, VentanaInformacionEmpleado):
        VentanaInformacionEmpleado.setObjectName("VentanaInformacionEmpleado")
        VentanaInformacionEmpleado.resize(443, 314)
        self.gridLayout = QtWidgets.QGridLayout(VentanaInformacionEmpleado)
        self.gridLayout.setObjectName("gridLayout")
        self.panelSur = QtWidgets.QWidget(VentanaInformacionEmpleado)
        self.panelSur.setObjectName("panelSur")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.panelSur)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.botonGuardarEmpleado = QtWidgets.QPushButton(self.panelSur)
        self.botonGuardarEmpleado.setObjectName("botonGuardarEmpleado")
        self.horizontalLayout.addWidget(self.botonGuardarEmpleado)
        self.botonCancelar = QtWidgets.QPushButton(self.panelSur)
        self.botonCancelar.setObjectName("botonCancelar")
        self.horizontalLayout.addWidget(self.botonCancelar)
        self.gridLayout.addWidget(self.panelSur, 1, 0, 1, 1)
        self.panelCentro = QtWidgets.QWidget(VentanaInformacionEmpleado)
        self.panelCentro.setObjectName("panelCentro")
        self.formLayout_2 = QtWidgets.QFormLayout(self.panelCentro)
        self.formLayout_2.setObjectName("formLayout_2")
        self.etiquetaNombre = QtWidgets.QLabel(self.panelCentro)
        self.etiquetaNombre.setObjectName("etiquetaNombre")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.etiquetaNombre)
        self.campoNombre = QtWidgets.QLineEdit(self.panelCentro)
        self.campoNombre.setObjectName("campoNombre")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.campoNombre)
        self.etiquetaApellidoPaterno = QtWidgets.QLabel(self.panelCentro)
        self.etiquetaApellidoPaterno.setObjectName("etiquetaApellidoPaterno")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.etiquetaApellidoPaterno)
        self.campoApellidoPaterno = QtWidgets.QLineEdit(self.panelCentro)
        self.campoApellidoPaterno.setObjectName("campoApellidoPaterno")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.campoApellidoPaterno)
        self.etiquetaApellidoMaterno = QtWidgets.QLabel(self.panelCentro)
        self.etiquetaApellidoMaterno.setObjectName("etiquetaApellidoMaterno")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.etiquetaApellidoMaterno)
        self.campoApellidoMaterno = QtWidgets.QLineEdit(self.panelCentro)
        self.campoApellidoMaterno.setObjectName("campoApellidoMaterno")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.campoApellidoMaterno)
        self.campoNoEmpleado = QtWidgets.QLineEdit(self.panelCentro)
        self.campoNoEmpleado.setObjectName("campoNoEmpleado")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.campoNoEmpleado)
        self.etiquetaNoEmpleado = QtWidgets.QLabel(self.panelCentro)
        self.etiquetaNoEmpleado.setObjectName("etiquetaNoEmpleado")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.etiquetaNoEmpleado)
        self.tiempoEntrada = QtWidgets.QTimeEdit(self.panelCentro)
        self.tiempoEntrada.setObjectName("tiempoEntrada")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.tiempoEntrada)
        self.etiquetaHoraEntrada = QtWidgets.QLabel(self.panelCentro)
        self.etiquetaHoraEntrada.setObjectName("etiquetaHoraEntrada")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.etiquetaHoraEntrada)
        self.etiquetaHoraSalida = QtWidgets.QLabel(self.panelCentro)
        self.etiquetaHoraSalida.setObjectName("etiquetaHoraSalida")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.etiquetaHoraSalida)
        self.tiempoSalida = QtWidgets.QTimeEdit(self.panelCentro)
        self.tiempoSalida.setObjectName("tiempoSalida")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.tiempoSalida)
        self.gridLayout.addWidget(self.panelCentro, 0, 0, 1, 1)

        self.retranslateUi(VentanaInformacionEmpleado)
        QtCore.QMetaObject.connectSlotsByName(VentanaInformacionEmpleado)

    def retranslateUi(self, VentanaInformacionEmpleado):
        _translate = QtCore.QCoreApplication.translate
        VentanaInformacionEmpleado.setWindowTitle(_translate("VentanaInformacionEmpleado", "Nuevo empleado"))
        self.botonGuardarEmpleado.setText(_translate("VentanaInformacionEmpleado", "Guardar"))
        self.botonCancelar.setText(_translate("VentanaInformacionEmpleado", "Cancelar"))
        self.etiquetaNombre.setText(_translate("VentanaInformacionEmpleado", "Nombre:"))
        self.etiquetaApellidoPaterno.setText(_translate("VentanaInformacionEmpleado", "Apellido paterno:"))
        self.etiquetaApellidoMaterno.setText(_translate("VentanaInformacionEmpleado", "Apellido materno:"))
        self.etiquetaNoEmpleado.setText(_translate("VentanaInformacionEmpleado", "No. de empleado:"))
        self.tiempoEntrada.setDisplayFormat(_translate("VentanaInformacionEmpleado", "hh:mm"))
        self.etiquetaHoraEntrada.setText(_translate("VentanaInformacionEmpleado", "Hora de entrada:"))
        self.etiquetaHoraSalida.setText(_translate("VentanaInformacionEmpleado", "Hora de salida:"))
        self.tiempoSalida.setDisplayFormat(_translate("VentanaInformacionEmpleado", "hh:mm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaInformacionEmpleado = QtWidgets.QWidget()
    ui = Ui_VentanaInformacionEmpleado()
    ui.setupUi(VentanaInformacionEmpleado)
    VentanaInformacionEmpleado.show()
    sys.exit(app.exec_())
