# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaControlAsistencia.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, VentanaControlAsistencia):
        VentanaControlAsistencia.setObjectName("VentanaControlAsistencia")
        VentanaControlAsistencia.setGeometry(QtCore.QRect(0, 0, 456, 344))
        self.gridLayout = QtWidgets.QGridLayout(VentanaControlAsistencia)
        self.gridLayout.setObjectName("gridLayout")
        self.botonSalir = QtWidgets.QPushButton(VentanaControlAsistencia)
        self.botonSalir.setObjectName("botonSalir")
        self.gridLayout.addWidget(self.botonSalir, 2, 0, 1, 2)
        self.botonRegistrarLlegada = QtWidgets.QPushButton(VentanaControlAsistencia)
        self.botonRegistrarLlegada.setObjectName("botonRegistrarLlegada")
        self.gridLayout.addWidget(self.botonRegistrarLlegada, 1, 0, 1, 1)
        self.botonRegistrarSalida = QtWidgets.QPushButton(VentanaControlAsistencia)
        self.botonRegistrarSalida.setObjectName("botonRegistrarSalida")
        self.gridLayout.addWidget(self.botonRegistrarSalida, 1, 1, 1, 1)

        self.retranslateUi(VentanaControlAsistencia)
        QtCore.QMetaObject.connectSlotsByName(VentanaControlAsistencia)

    def retranslateUi(self, VentanaControlAsistencia):
        _translate = QtCore.QCoreApplication.translate
        VentanaControlAsistencia.setWindowTitle(_translate("Form", "Control de asistencia"))
        self.botonSalir.setText(_translate("Form", "Salir"))
        self.botonRegistrarLlegada.setText(_translate("Form", "Registrar llegada"))
        self.botonRegistrarSalida.setText(_translate("Form", "Registrar salida"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaControlAsistencia = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(VentanaControlAsistencia)
    VentanaControlAsistencia.show()
    sys.exit(app.exec_())
